name: Deploy Cloud Clicker to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
  
      # Set up Python 3.* environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
  
      # Elastic Beanstalk CLI version
      - name: Get EB CLI version
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
  
  
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      # Create the Elastic Beanstalk application
      - name: Create EBS application
        run: |
          eb init -p docker CloudClick --region ${{ secrets.AWS_REGION }}
  
      # Deploy to (or Create) the Elastic Beanstalk environment
      - name: Create environment & deploy
        run: |
          if eb status CloudClickEnv; then
            eb use CloudClickEnv
            eb deploy
          else
            eb create CloudClickEnv --single
          fi