name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive project files
      run: zip -r my-app.zip . -x ".git/*" ".github/*" "venv/*" "*.DS_Store"

    - name: Upload to S3
      run: |
        aws s3 cp my-app.zip s3://${{ secrets.S3_BUCKET }}/my-app.zip

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        pip install awsebcli

    - name: Initialize Elastic Beanstalk
      run: |
        eb init -p python-3.8 ${{ secrets.EB_APP_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Create Elastic Beanstalk application version
      run: |
        VERSION_LABEL="app-$(date +'%Y%m%d_%H%M%S')"
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APP_NAME }} \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=my-app.zip

    - name: Deploy to Elastic Beanstalk
      run: |
        VERSION_LABEL="app-$(date +'%Y%m%d_%H%M%S')"
        eb deploy ${{ secrets.EB_ENV_NAME }} --version $VERSION_LABEL
